# TP1 DA SILVA PEREIRA Théo

In [1]:
import numpy as np
from math import sqrt
import sympy as sp
import pygame

pygame 2.6.1 (SDL 2.28.4, Python 3.12.7)
Hello from the pygame community. https://www.pygame.org/contribute.html


# Exercice 6.1 Le but de cet exercice est de créer deux fonctions, une qui associe le vecteur colonne dans la base canonique à une matrice de $M_m,_n$ (K) et l’autre qui fait l’opération inverse.

## 1. Soit A $ \in M_m,_n$ (K) et V le vecteur colonne associé. Quelle est la dimension de V ? Quelle est la relation entre les $V_k$ et les $A_i,_j$ ?

V est de dimmension 1

## 2. Écrire une fonction colonne Vecteur_Colonne(A) qui prend en entrée une matrice et retourne le vecteur associé de la bonne taille.

In [2]:
def Vecteur_Colonne(A):
    V = np.zeros(A.shape[1]*A.shape[0])
    cpt = 0
    for i in range(A.shape[1]):
        for j in A:
            V[cpt] = j[i]
            cpt = cpt+1
    return V

A = np.array([[1, 2, 3], [4, 5, 6]])
V = Vecteur_Colonne(A)
print(V)

[1. 4. 2. 5. 3. 6.]


## 3. Écrire la fonction Matrice(V) qui prend en entrée un vecteur ligne de taille n² et retourne la matrice de taille n x n correspondante.

In [3]:
def Matrice(V):
    n = sqrt(V.shape[0])
    if not n%1 == 0:
        print("Erreur : la matrice n'est pas une matrice carrée")
        return 0

    n = int(n)
    A = np.zeros([n,n])

    cpt = 0

    for i in range(n):
        for j in range(n):
            A[j,i] = V[cpt]
            cpt = cpt + 1
    return A

V2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
Verror = np.array([1, 2, 3])

print("Test de la fonction avec une matrice carrée :")
print(Matrice(V2))

print("\nTest de la fonction avec une matrice qui n'est pas une matrice carrée")
print(Matrice(Verror))

Test de la fonction avec une matrice carrée :
[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]

Test de la fonction avec une matrice qui n'est pas une matrice carrée
Erreur : la matrice n'est pas une matrice carrée
0


# Exercice 6.2 (Création des matrices croix). Créer une fonction Croix($_i,_j,_n$) qui crée la matrice C_i,_j de taille n² avec des 1 seulement en (i,j) et les voisins verticaux et horizontaux. Il y aura des zéros aux autres positions.

In [4]:
def Croix(i, j, n):
    A = np.zeros([n, n])
    
    if not (i >=0 and j >= 0 and i < n and j < n):
        print(f"Erreur : le point de coordonnée {i, j} n'est pas dans la matrice carrée de taille {n}")
        return 0

    # Point central
    A[j, i] = 1

    # Gauche
    if i-1 >= 0:
        A[j, i-1] = 1

    # Droite
    if i+1 < n:
        A[j, i+1] = 1
    
    # Haut
    if j-1 >= 0:
        A[j-1, i] = 1
    
    # Bas
    if j+1 < n:
        A[j+1, i] = 1

    return A

Croix(1, 1, 3)

array([[0., 1., 0.],
       [1., 1., 1.],
       [0., 1., 0.]])

# Exercice 6.3 (Jeu 3X3). Dans cette question, on veut demande de créer un fonction Lights_Out() sans variable d’entrée qui lance le jeu avec les indications :

1. Phrase d’accueil dans le jeu,
2. Tirage d’une configuration aléatoire avec la commande random.randint() de Numpy,
3. Achage de la configuration initiale,
4. Demande de la case où le joueur veut jouer
5. Récupération du numéro de ligne et de colonne avec la commande input()
6. Mise à jour de la configuration et achage de celle-ci
7. On continue jusqu’à ce que le joueur éteigne toutes les lampes et dans ce cas, on affiche un message de félicitations et on sort du jeu.

In [5]:
def Lights_Out():
    # Message de d'accueil
    print("Bienvenue dans Lights Out! Le but du jeu est de remplir la matrice de \"0\".")
    print("Pour cela vous entrerez des coordonnées (x,y) sur lequel placer votre point.") 
    print("Cela placera une croix qui changera les 1 par des 0 et les 0 par des 1")

    n = int(input("Entrez la taille de la matrice carré que vous souhaitez (minimum 2) :"))

    while n < 2:
        n = int(input("Entrez un nombre supérieur ou égale à 2 :"))

    # Création aléatoire d'une matrice initale
    M = np.zeros([n, n])
    for i in range(n):
        for j in range(n):
            M[j, i] = np.random.randint(2)
    
    # Création de la matrice finale à obtenir
    Mfinale = np.full([n, n], 0)
    
    # Affichage de la matrice initiale
    print("\nVoici la matrice initiale :\n", M)

    # Entrée de la colonne et ligne par l'utilisateur
    x, y = input("Entrez la colonne et la ligne que vous voulez jouer séparées par un espace :").split()
    x = int(x)
    y = int(y)
    
    # Création d'une matrice croix
    Mcroix = Croix(x, y, n)

    M = (M + Mcroix)%2
    print("\nNouvelle configuration :\n",M)

    
    while(not np.array_equal(M, Mfinale)):
        # Entrée de la colonne et ligne par l'utilisateur
        x, y = input("Entrez la colonne et la ligne que vous voulez jouer séparées par un espace :").split()
        x = int(x)
        y = int(y)

        # /!\ Faire verif de x et y
        
        # Création d'une matrice croix
        Mcroix = Croix(x, y, n)

        M = (M + Mcroix)%2
        print("\nNouvelle configuration :\n",M)

    # Le joueur a remplis la matrice de 0
    print("Bien joué ! Vous avez gagné")
#Lights_Out()

# Exercice 6.4 (Matrice de passage). Créer une fonction Matrice_Passage(n) qui prend en entrée la dimension n et retourne la matrice dont les vecteurs sont les $C_i,_j$ exprimées dans la base canonique de $M_n(F_2)$. On prendra les $C_i,_j$ dans le même ordre que les vecteurs $E_i,_j$ de la base canonique.

In [6]:
def Matrice_Passage(n):
    matrice_passage = np.zeros((n*n, n*n))
    
    for i in range(n):
        for j in range(n):
            matrice_passage[:, j * n + i] = Croix(i, j, n).flatten()
    
    return matrice_passage

print(Matrice_Passage(3))


[[1. 1. 0. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 1. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 1. 1. 0. 1. 0. 0.]
 [0. 1. 0. 1. 1. 1. 0. 1. 0.]
 [0. 0. 1. 0. 1. 1. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 1. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1. 0. 1. 1.]]


# Exercice 6.5. On veut déterminer pour quelles dimensions, le jeu a toujours une solution.

1. Écrire une boucle qui calcule pour n = 2 à 11, le déterminant de Matrice_Passage(n). On rappelle que ce déterminant est un nombre dans F2 , c’est-à-dire 0 ou 1. Comme Python fait les calculs avec nombres à virgule flottante, il pourra être utile d’utiliser les commandes round(), int() et ajouter %2 pour avoir le reste dans la division euclidienne par 2.
2. Donner la liste des dimensions inférieures à 11 pour lesquelles le jeu possède une solution unique pour toute configuration initiale

In [7]:
solutions = []

for n in range(2, 12):
    matrice_passage = Matrice_Passage(n)
    det = int(round(np.linalg.det(matrice_passage))) % 2
    if det != 0:
        solutions.append(n)
    print("n = ", n, "det = ", det)

print("Solutions :", solutions)


n =  2 det =  1
n =  3 det =  1
n =  4 det =  0
n =  5 det =  0
n =  6 det =  1
n =  7 det =  1
n =  8 det =  1
n =  9 det =  0
n =  10 det =  1
n =  11 det =  0
Solutions : [2, 3, 6, 7, 8, 10]


# Exercice 6.6 (Inverse de la matrice de passage en dimension 3). Grâce à Python, calculer l’inverse de la matrice de passage en dimension 3 dans. On pourra soit faire les calculs dans R avec la commande linalg.inv() de Numpy, se ramener aux entiers puis réduire modulo 2 ou charger le package Sympy, changer le type de la matrice avec Matrix() et calculer l’inverse dans $M(F_2)$ avec la méthode .inv_mod(2).

In [8]:
def InverseMatricePassage(M):
    return sp.Matrix(M).inv_mod(2)

sp.pretty_print(InverseMatricePassage(Matrice_Passage(3)))

⎡1  0  1  0  0  1  1  1  0⎤
⎢                         ⎥
⎢0  0  0  0  1  0  1  1  1⎥
⎢                         ⎥
⎢1  0  1  1  0  0  0  1  1⎥
⎢                         ⎥
⎢0  0  1  0  1  1  0  0  1⎥
⎢                         ⎥
⎢0  1  0  1  1  1  0  1  0⎥
⎢                         ⎥
⎢1  0  0  1  1  0  1  0  0⎥
⎢                         ⎥
⎢1  1  0  0  0  1  1  0  1⎥
⎢                         ⎥
⎢1  1  1  0  1  0  0  0  0⎥
⎢                         ⎥
⎣0  1  1  1  0  0  1  0  1⎦


# Exercice 6.7 (Solutionneur en dimension 3). Écrire une fonction Solution(A) qui prend en entrée une configuration initiale sous forme d’une matrice 3 * 3 A et retourne une matrice solution S (qui contient des 1 pour les cases où il faut appuyer et des 0 ailleurs).

In [9]:
def Solution(A):
    V = Vecteur_Colonne(A)
    S_vect = InverseMatricePassage(Matrice_Passage(3)) * sp.Matrix(V) % 2
    return Matrice(S_vect)

A = np.array([
    [1, 0, 0],
    [0, 0, 0],
    [0, 0, 0]])
S = Solution(A)
print(S)

[[1. 0. 1.]
 [0. 0. 1.]
 [1. 1. 0.]]


# Exercice 6.8 (Bonus). Créer une interface graphique pour le jeu grâce à la bibliothèque Pygame. On pourra le faire en dimension 3 puis laisser le choix de la dimension au joueur, ajouter un bouton pour afficher la solution (Dans ce cas, on tirera la solution au hasard et la configuration initiale sera son image par la matrice de passage). 

In [45]:
from tkinter import messagebox
from tkinter import Tk, Button, Label
n = 0

def set_size(size):
    global n
    n = size
    window.destroy()

# Initialisation de la fenêtre de choix de la taille de la matrice
window = Tk()

# Définition du titre de la fenêtre
window.title("Choix de la taille de la matrice")

# Définition des dimensions de la fenêtre
window.geometry("200x350")

# Focus sur la fenêtre après 1ms
window.after(1, lambda: window.focus_force())

# Centrage de la fenêtre
window.eval('tk::PlaceWindow . center')

# Label de la fenêtre
label = Label(window, text="Choisissez la taille de la matrice")
label.pack(pady=10)

# Création des boutons
btn = Button(window, text="2", command=lambda: set_size(2))
btn.pack(pady=10)

btn = Button(window, text="3", command=lambda: set_size(3))
btn.pack(pady=10)

for size in range(6, 9):
    btn = Button(window, text=str(size), command=lambda: set_size(size))
    btn.pack(pady=10)

btn = Button(window, text="10", command=lambda: set_size(10))
btn.pack(pady=10)

# Affichage de la fenêtre
window.mainloop()


# Si l'utilisateur a choisi une taille (et non pas fermé la fenêtre)
if n != 0:
    # pygame setup
    pygame.init()
    cell_size = 150  # Taille de chaque cellule
    if n == 10:
        cell_size = 100 # Adaptation de la taille des cellules pour n = 10

    screen_size = n * cell_size
    screen = pygame.display.set_mode((screen_size, screen_size + 50))  # Augmenter la hauteur pour le bouton
    pygame.display.set_caption("Lights Out")
    clock = pygame.time.Clock()
    running = True

    # Initialisation de la matrice de jeu
    def Matrice_Aleatoire(n):
        M = np.zeros([n, n])
        for i in range(n):
            for j in range(n):
                M[j, i] = np.random.randint(2)
        return M
    M = Matrice_Aleatoire(n)

    def draw_grid():
        for x in range(0, screen_size, cell_size):
            for y in range(0, screen_size, cell_size):
                rect = pygame.Rect(x, y, cell_size, cell_size)
                if M[y // cell_size, x // cell_size] == 1:
                    color = (255, 255, 255)
                else:
                    color = (0, 0, 0)
                pygame.draw.rect(screen, color, rect)
                pygame.draw.rect(screen, (200, 200, 200), rect, 1) # Contour des cases

    def toggle_cells(x, y):
        global M
        Mcroix = Croix(x, y, n)
        M = (M + Mcroix) % 2

    # Ajouter un bouton "Solution"
    font = pygame.font.Font(None, 36)
    solution_button = pygame.Rect(screen_size - 150, screen_size, 140, 40)

    def draw_solution_button():
        pygame.draw.rect(screen, (0, 128, 0), solution_button)
        text = font.render("Solution", True, (255, 255, 255))
        screen.blit(text, (solution_button.x + 10, solution_button.y + 5))

    def check_win():
        if np.all(M == 0):
            messagebox.showinfo("Win", "Vous avez gagné !\nUne nouvelle grille va être générée.")
            return True
        return False
            
    def Solution(A):
        V = Vecteur_Colonne(A)
        S_vect = InverseMatricePassage(Matrice_Passage(n)) * sp.Matrix(V) % 2
        return Matrice(S_vect)   

    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            elif event.type == pygame.MOUSEBUTTONDOWN:
                mouse_x, mouse_y = event.pos
                if solution_button.collidepoint(mouse_x, mouse_y):
                    messagebox.showinfo("Solution", f"La solution est :\n{Solution(M).astype(int)}")
                else:
                    grid_x = mouse_x // cell_size
                    grid_y = mouse_y // cell_size
                    toggle_cells(grid_x, grid_y)

        screen.fill((0, 0, 0))
        draw_grid()
        draw_solution_button()
        pygame.display.flip()
        if check_win():
            M = Matrice_Aleatoire(n)
        clock.tick(60)


    pygame.quit()