# TP1 DA SILVA PEREIRA Théo

In [1]:
import numpy as np
from math import sqrt

# Exercice 6.1 Le but de cet exercice est de créer deux fonctions, une qui associe le vecteur colonne dans la base canonique à une matrice de $M_m,_n$ (K) et l’autre qui fait l’opération inverse.

## 1. Soit A $ \in M_m,_n$ (K) et V le vecteur colonne associé. Quelle est la dimension de V ? Quelle est la relation entre les $V_k$ et les $A_i,_j$ ?

V est de dimmension 1

## 2. Écrire une fonction colonne Vecteur_Colonne(A) qui prend en entrée une matrice et retourne le vecteur associé de la bonne taille.

In [2]:
def Vecteur_Colonne(A):
    V = np.zeros(A.shape[1]*A.shape[0])
    cpt = 0
    for i in range(A.shape[1]):
        for j in A:
            V[cpt] = j[i]
            cpt = cpt+1
    return V

A = np.array([[1, 2, 3], [4, 5, 6]])
V = Vecteur_Colonne(A)
print(V)

[1. 4. 2. 5. 3. 6.]


## 3. Écrire la fonction Matrice(V) qui prend en entrée un vecteur ligne de taille n² et retourne la matrice de taille n x n correspondante.

In [3]:
def Matrice(V):
    n = sqrt(V.shape[0])
    if not n%1 == 0:
        print("Erreur : la matrice n'est pas une matrice carrée")
        return 0

    n = int(n)
    A = np.zeros([n,n])

    cpt = 0

    for i in range(n):
        for j in range(n):
            A[j,i] = V[cpt]
            cpt = cpt + 1
    return A

V2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
Verror = np.array([1, 2, 3])

print("Test de la fonction avec une matrice carrée :")
print(Matrice(V2))

print("\nTest de la fonction avec une matrice qui n'est pas une matrice carrée")
print(Matrice(Verror))

Test de la fonction avec une matrice carrée :
[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]

Test de la fonction avec une matrice qui n'est pas une matrice carrée
Erreur : la matrice n'est pas une matrice carrée
0


# Exercice 6.2 (Création des matrices croix). Créer une fonction Croix($_i,_j,_n$) qui crée la matrice C_i,_j de taille n² avec des 1 seulement en (i,j) et les voisins verticaux et horizontaux. Il y aura des zéros aux autres positions.

In [4]:
def Croix(i, j, n):
    A = np.zeros([n, n])
    
    if not (i >=0 and j >= 0 and i < n and j < n):
        print(f"Erreur : le point de coordonnée {i, j} n'est pas dans la matrice carrée de taille {n}")
        return 0

    # Point central
    A[j, i] = 1

    # Gauche
    if i-1 >= 0:
        A[j, i-1] = 1

    # Droite
    if i+1 < n:
        A[j, i+1] = 1
    
    # Haut
    if j-1 >= 0:
        A[j-1, i] = 1
    
    # Bas
    if j+1 < n:
        A[j+1, i] = 1

    return A

Croix(1, 1, 3)

array([[0., 1., 0.],
       [1., 1., 1.],
       [0., 1., 0.]])

# Exercice 6.3 (Jeu 3X3). Dans cette question, on veut demande de créer un fonction Lights_Out() sans variable d’entrée qui lance le jeu avec les indications :

1. Phrase d’accueil dans le jeu,
2. Tirage d’une configuration aléatoire avec la commande random.randint() de Numpy,
3. Achage de la configuration initiale,
4. Demande de la case où le joueur veut jouer
5. Récupération du numéro de ligne et de colonne avec la commande input()
6. Mise à jour de la configuration et achage de celle-ci
7. On continue jusqu’à ce que le joueur éteigne toutes les lampes et dans ce cas, on affiche un message de félicitations et on sort du jeu.

In [21]:
def Lights_Out():
    # Message de d'accueil
    print("Bienvenue dans Lights Out! Le but du jeu est de remplir la matrice de \"1\".")
    print("Pour cela vous entrerez des coordonnées (x,y) sur lequel placer votre point.") 
    print("Cela placera une croix qui changera les 1 par des 0 et les 0 par des 1")

    n = int(input("Entrez la taille de la matrice carré que vous souhaitez (minimum 3) :"))

    # /!\ Verif n

    # Création aléatoire d'une matrice initale
    M = np.zeros([n, n])
    for i in range(n):
        for j in range(n):
            M[j, i] = np.random.randint(2)
    
    # Création de la matrice finale à obtenir
    Mfinale = np.full([n, n], 1)
    
    # Affichage de la matrice initiale
    print("\nVoici la matrice initiale :\n", M)

    # Entrée de la colonne et ligne par l'utilisateur
    x, y = input("Entrez la colonne et la ligne que vous voulez jouer séparées par un espace :").split()
    x = int(x)
    y = int(y)

    # /!\ Faire verif de x et y
    
    # Création d'une matrice croix
    Mcroix = Croix(x, y, n)

    M = (M + Mcroix)%2
    print("\nNouvelle configuration :\n",M)

    
    while(not np.array_equal(M, Mfinale)):
        # Entrée de la colonne et ligne par l'utilisateur
        x, y = input("Entrez la colonne et la ligne que vous voulez jouer séparées par un espace :").split()
        x = int(x)
        y = int(y)

        # /!\ Faire verif de x et y
        
        # Création d'une matrice croix
        Mcroix = Croix(x, y, n)

        M = (M + Mcroix)%2
        print("\nNouvelle configuration :\n",M)

    # Le joueur a remplis la matrice de 1
    print("Bien joué ! Vous avez gagné")
Lights_Out()

Bienvenue dans Lights Out! Le but du jeu est de remplir la matrice de "1".
Pour cela vous entrerez des coordonnées (x,y) sur lequel placer votre point.
Cela placera une croix qui changera les 1 par des 0 et les 0 par des 1

Voici la matrice initiale :
 [[1. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Nouvelle configuration :
 [[1. 0. 0.]
 [1. 1. 1.]
 [0. 1. 0.]]

Nouvelle configuration :
 [[1. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Nouvelle configuration :
 [[1. 0. 0.]
 [1. 1. 1.]
 [0. 1. 0.]]


ValueError: not enough values to unpack (expected 2, got 0)

# Exercice 6.4 (Matrice de passage). Créer une fonction Matrice_Passage(n) qui prend en entrée la dimension n et retourne la matrice dont les vecteurs sont les $C_i,_j$ exprimées dans la base canonique de $M_n(F_2)$. On prendra les $C_i,_j$ dans le même ordre que les vecteurs $E_i,_j$ de la base canonique.

In [11]:
import numpy as np

def Matrice_Passage(n):
    # Nombre total d'éléments dans une matrice n x n
    taille = n * n
    # Créer une matrice vide de dimension (n^2, n^2)
    matrice_passage = np.zeros((taille, taille), dtype=int)
    
    # Remplir la matrice avec les matrices E_{i,j} aplaties
    for i in range(n):
        for j in range(n):
            # Position du vecteur dans la base canonique
            index = i * n + j
            # Créer une matrice E_{i,j} avec des 0 partout sauf à la position (i, j)
            E = np.zeros((n, n), dtype=int)
            E[i, j] = 1
            # Aplatir la matrice E et la placer dans la colonne correspondante
            matrice_passage[:, index] = E.flatten()
    
    return matrice_passage

# Exemple d'utilisation avec n = 2
n = 2
matrice = Matrice_Passage(n)
print(matrice)


[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [10]:
import numpy as np

def Matrice_Passage(n):
    # Initialiser une matrice vide de taille n^2 x n^2
    matrice = np.zeros((n*n, n*n), dtype=int)
    
    # Remplir la matrice avec les vecteurs C_ij (déroulés des matrices élémentaires E_ij)
    for i in range(n):
        for j in range(n):
            # Construire la matrice élémentaire E_ij
            E_ij = np.zeros((n, n), dtype=int)
            E_ij[i, j] = 1  # Placer un "1" à la position (i, j)
            # Dérouler la matrice E_ij en un vecteur de longueur n^2
            vecteur_C_ij = E_ij.flatten()            
            # Placer ce vecteur dans la matrice de passage
            matrice[i*n + j, :] = vecteur_C_ij
    
    return matrice

print("\n", Matrice_Passage(2))


 [[1 0]
 [0 0]]

 [1 0 0 0]

 [[0 1]
 [0 0]]

 [0 1 0 0]

 [[0 0]
 [1 0]]

 [0 0 1 0]

 [[0 0]
 [0 1]]

 [0 0 0 1]

 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [12]:
def Matrice_Passage(n):
    matrice_passage = np.zeros((n*n, n*n))
    index = 0
    for i in range(n):
        for j in range(n):
            matrice_passage[index, i*n+j] = 1
            index += 1
    return matrice_passage

print(Matrice_Passage(2))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
