# TP2 DA SILVA PEREIRA Théo

In [74]:
import numpy as np
import matplotlib.pyplot as plt

# 4.1 Création des matrices utilisées

## <u>Exercice 4.1</u> :
Créer une fonction point_vecteur(p) qui prend en entrée un point p de coordonnées (x,y) et retourne le vecteur [x, y, 1].

In [75]:
def point_vecteur(p):
    return np.array([p[0], p[1], 1])

point_vecteur(np.array([1, 2]))

array([1, 2, 1])

# <u>Exercice 4.2</u> : 

Créer une fonction repere_projectif(p_1,p_2,p_3,p_4) qui prend en entrée 4 points $p_i = ( x_i , y_i )$ de R² et retourne un booléen selon que les 4 points forment un repère projectif ou non.

In [76]:
def repere_projectif(p_1, p_2, p_3, p_4):
    v1 = point_vecteur(p_1)
    v2 = point_vecteur(p_2)
    v3 = point_vecteur(p_3)
    v4 = point_vecteur(p_4)

    if np.linalg.det(np.array([v1, v2, v3])) != 0:
        if np.linalg.det(np.array([v1, v2, v4])) != 0:
            if np.linalg.det(np.array([v1, v3, v4])) != 0:
                if np.linalg.det(np.array([v2, v3, v4])) != 0:
                    return True
    
    return False

p1 = np.array([0, 1])
p2 = np.array([0, 2])
p3 = np.array([0, 1])
p4 = np.array([2, 2])
print(repere_projectif(p1, p2, p3, p4)) # p1, p2, p3 sont alignés


p1 = np.array([1, 1])
p2 = np.array([1, 2])
p3 = np.array([2, 1])
p4 = np.array([2, 2])
print(repere_projectif(p1, p2, p3, p4)) # aucun point n'est aligné



False
True


# <u>Exercice 4.3</u> :
Créer une fonction matrice_A(p_1,p_2,p_3,p_4) qui prend en entrée 4 points $p_i = (x_i, y_i) de R²$ et retourne la matrice A de la Section 2.6.

In [77]:
p1 = np.array([0, 0])
p2 = np.array([1, 0])
p3 = np.array([0, 1])
p4 = np.array([1, 1])

p1_prime = np.array([0, 0])
p2_prime = np.array([3, 1])
p3_prime = np.array([2, 1])
p4_prime = np.array([5, 3/2])


def matrice_A(p_1, p_2, p_3, p_4):
    return np.transpose(np.array([point_vecteur(p_1), point_vecteur(p_2), point_vecteur(p_3)]))

matrice_A(p1, p2, p3, p4)

array([[0, 1, 0],
       [0, 0, 1],
       [1, 1, 1]])

# <u>Exercice 4.4</u> :
Créer une fonction matrice_B(p_1,p_2,p_3,p_4) qui prend en entrée 4 points $p_i = (x_i, y_i) de R²$ et retourne la matrice B de la Section 2.6.

In [78]:
def matrice_B(p_1, p_2, p_3, p_4):
    return np.linalg.inv(matrice_A(p_1, p_2, p_3, p_4))

print(matrice_B(p1, p2, p3, p4), "\n")

print(np.dot(matrice_A(p1, p2, p3, p4), matrice_B(p1, p2, p3, p4))) # A*B = I

[[-1. -1.  1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# <u>Exercice 4.5</u> :
Créer une fonction matrice_D(p_1,p_2,p_3,p_4) qui prend en entrée 4 points $p_i = (x_i, y_i) de R²$ et retourne la matrice C de la Section 2.6.

In [79]:
def matrice_C(p_1, p_2, p_3, p_4):
    vec_lambda = np.dot(matrice_B(p_1, p_2, p_3, p_4), point_vecteur(p_4))
    vec_lambda = np.diag(vec_lambda)
    return np.dot(matrice_A(p1, p2, p3, p4), vec_lambda)

matrice_C(p1, p2, p3, p4)

array([[ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [-1.,  1.,  1.]])

# <u>Exercice 4.6</u> :
Créer une fonction matrice_passage(p_1,p_2,p_3,p_4,p_1,p_2,p_3,p_4) qui en prend en entrée 2 quadruplets de points, vérifie qu’ils forment des repères projectifs, si oui retourne la matrice P de la Section et sinon lève une erreur avec une commande du type
```py
if condition:
    raise ValueError("Message derreur")
```

In [80]:
def matrice_passage(p_1, p_2, p_3, p_4, p_1_prime, p_2_prime, p_3_prime, p_4_prime):
    if not repere_projectif(p_1, p_2, p_3, p_4) or not repere_projectif(p_1_prime, p_2_prime, p_3_prime, p_4_prime):
        raise ValueError("Les points ne forment pas un repère projectif")
    
    matrice_C_prime = matrice_C(p_1_prime, p_2_prime, p_3_prime, p_4_prime)
    #print(matrice_C_prime)
    
    C = matrice_C(p_1, p_2, p_3, p_4)
    #print(C)

    matrice_inv_C = np.linalg.inv(C)
    #print(matrice_inv_C)

    return np.dot(matrice_C_prime, matrice_inv_C)

matrice_passage([0, 0], [1, 0], [0, 1], [1, 1], [0, 0], [3, 1], [2, 1], [5, 3/2])

array([[ 2. ,  0. ,  0. ],
       [ 0. , -0.5,  0. ],
       [ 1.5, -1. ,  0.5]])

# <u>Exercice 4.7</u> :
Créer une fonction rectification_projective_A4(p_1,p_2,p_3,p_4,image) qui prend en entrée 4 points (p_1 , p_2 , p_3 , p_4 ) d’une image (préalablement importée avec une commande du type image = plt.imread("image.jpg") et retourne une image au format A4 où le quadrilatère de sommets p_1 , p_2 , p_3 , p_4 a été redressé sur la nouvelle image au format A

In [88]:
def g(x, y, P):
    vec = np.dot(P, np.array([x, y, 1]))
    return np.array([vec[0]/vec[2], vec[1]/vec[2]])

In [ ]:
def rectification_projective_A4(p_1, p_2, p_3, p_4):
    nouvelle_image=np.zeros((594,420, 3), dtype = np.uint8)

    P = matrice_passage(p_1, p_2, p_3, p_4, [0, 0], [420, 0], [0, 594], [420, 594])
    p1_prime = g(p_1[0], p_1[1], P)
    p2_prime = g(p_2[0], p_2[1], P)
    p3_prime = g(p_3[0], p_3[1], P)
    p4_prime = g(p_4[0], p_4[1], P)

    print (P)   
    

rectification_projective_A4(p1, p2, p3, p4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
